---
- hosts: ubuntuserver
  become: yes
  tasks:
    - name: Install apache2 on ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Start apache2 on ubuntu
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
    
    - name: Start httpd on amazon linux
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"