---
- hosts: all
  become: yes
  tasks:
    - name: Install apache2 on ubuntu
      apt:
        name: apache2
        state: present
    - name: Start apache2 on ubuntu
      service:
        name: apache2
        state: started