---
- hosts: 172.31.46.11
  become: yes

  tasks:
  - name: Get the host name
    command: hostname -f
    register: hostdetails

  - name: print the details
    debug:
      msg: "{{hostdetails}}"

  - name: Install git
    apt:
      name: git
      state: present
    when: hostdetails.stderr ==""
  
  - name: Install tree
    apt:
      name: tree
      state: present
      when: hostdetails.stderr !=""
