---
- hosts: 172.31.46.11
  become: yes
  tasks:
  
  - include: myfile.yaml
  
  - name: Install webserver
    apt:
      name: apache2
      state: present
  - name: copy index file into node side
    copy:
      src: indexpage
      dest: /var/www/html/index.html
    notify: restart webserver
  
  - name: copy dynamic file into nodes
    template:
      src: dynamicfindex.j2
      dest: /var/www/html/index.html
    notify: restart webserver
  
  ########### Usage of Handlers ###################
  handlers:
  - name: restart webserver
    service:
      name: apache2
      state: restarted